#!/usr/bin/env python

from catkin.find_in_workspaces import find_in_workspaces

import os
import errno
import sys
import eclipsify_lib as eclipsify
from argparse import ArgumentParser, RawDescriptionHelpFormatter

usage="""
This utility creates a new eclipse project. It assumes the package is
in a workspace with the default names for the devel/build/src spaces.
If your workspace is different, try eclipsify-gen-project.

The project files will go to devel/share/project-name/eclipse"""

parser = ArgumentParser(description=usage,formatter_class=RawDescriptionHelpFormatter)

parser.add_argument("package", nargs=1, help="The name of the catkin package to be eclipsified.")

options = parser.parse_args()

package     = options.package[0]


libexec, share, src = find_in_workspaces(project=package)

build = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(libexec))),'build',package);

from eclipsify_lib.eclipsify_gen_project import main

main(argv=[package, src, os.path.join(share,'eclipse'), build]);
